enot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', views.index),
    url(r'^add/$', views.add_post, name='add_mass'),                        # добавление сообщения
    url(r'^edit/$', views.edit_post, name='edit_mass'),                     # изменение сообщения или комента сообщения
    url(r'^add_comm/$', views.add_comm, name='add_comm'),                   # добавление коммента
    url(r'^show_comm/$', views.show_comm, name='show_comm'),                # Подгрузить ветку с комментами
    url(r'^load_content/$', views.load_content, name='load_content'),       # Подгрузить очередную партию сообщений в ленту. 10 штук, но это не точно

]

test2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),

]

enot/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.
class Massages(models.Model):
    date=models.DateTimeField(auto_now=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    text_massage=models.TextField()
    def __str__(self):
        return str(self.id)


class Comments(models.Model):
    date=models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    text_massage=models.TextField()
    answer_massage=models.ForeignKey(Massages,on_delete=models.CASCADE,null=True,blank=True)
    answer_comment=models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)
    def __str__(self):
        return str(self.id)

enot/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Massages,Comments
import logging


count_post=0 #Количество сообщений которые загружены в ленту


def index(request):
	global count_post
	count_post=0
	return render(request,'enot/index.html')
	
  # Добавление поста  
def add_post(request):
	if request.user.is_authenticated() and request.user.is_active and request.method=="POST":
		Massages.objects.create(author=request.user,text_massage=request.POST.get('text_mass'))
	return HttpResponseRedirect('/')
	
 #Изменение поста или комментария
def edit_post(request):
	if request.user.is_authenticated() and request.user.is_active and request.method=="POST" :
		if request.POST.get('id_mass') != None:
			mass=Massages.objects.get(id=request.POST.get('id_mass'))
			if mass.author==request.user:		
				mass.text_massage=request.POST.get('text')
				mass.save()	
		if request.POST.get('id_comm') != None:
			comm=Comments.objects.get(id=request.POST.get('id_comm'))
			if comm.author==request.user:		
				comm.text_massage=request.POST.get('text')
				comm.save()
	return HttpResponse(True)
	
	# Добавление комментария к посту или к комментарию
def add_comm(request): 
	if request.user.is_authenticated() and request.user.is_active and request.method=="POST" :
		form=request.POST
		logging.debug('0')
		if form.get('mass'):
			logging.debug('m0')
			mass=Massages.objects.get(id=int(form.get("mass")))
			returnComm=Comments(author=request.user,text_massage=form.get('text_comm'),answer_massage=mass)
		if form.get('comm'):
			logging.debug('c0')
			comm=Comments.objects.get(id=int(form.get("comm")))
			returnComm=Comments(author=request.user,text_massage=form.get('text_comm'),answer_comment=comm)
		returnComm.save()
		returnComm=Comments.objects.filter(id=returnComm.id)                                                # Костыль, из-за того что шаблон ждет итерируемый объект
	return render(request,'enot/comments.html',{'comm':returnComm})

# Подгрузить комментарии к посту	
def show_comm(request): 
	if request.method=="POST" :
		comm=Comments.objects.filter(answer_massage=Massages.objects.get(id=int(request.POST.get('id_mass'))))
	return render(request,'enot/comments.html',{'comm':comm})
	
# Реализация "Бесконечной ленты"
def load_content(request):
	global count_post
	mass=Massages.objects.all().order_by('id').reverse()[count_post:10+count_post]
	if not len(mass):
		return HttpResponse ("")
	count_post+=10
	return render(request,'enot/content.html',{'mass':mass})	
	
	
	
	
	
	
	
	
	
	
	

logging.basicConfig(
	level = logging.DEBUG,
	format = '%(asctime)s %(levelname)s %(message)s',
)

enot/templates/enot/comments.html
{% load staticfiles %}
{%for c in comm%}
     <div class='comment' data-comm-id='{{c.id}}' > 
        <span class='header'>{{c.author.first_name}} {{c.author.last_name}}  <span> {{c.date|date:"G:i  j.n.Y"}}</span></span> 

            {% if user.is_authenticated%}
                <span class="add_comm_btn" data-index="0">Комментировать</span>
            {%endif%}
            {%ifequal c.author user%}
                <span class='edit' class='head'>Редактировать</span>
            {%endifequal%}
        <hr/>
        
        <div class='content'>{{c.text_massage}}</div>{% if c.comments_set.all%}<div class='plus' ><img data-index='0' class='plus_img' src='{% static "images/plus.jpg" %}'></div>{% endif%}
       {%with comm=c.comments_set.all template_name='enot/comments.html' %}
            {% include template_name %}
       {%endwith%}
    </div>
{% endfor%}
   

enot/templates/enot/content.html
{% for m in mass%}
                <div class="mas_wrap" data-mass-id='{{m.id}}'>
                    <div>
                    <span class='header'>{{m.author.first_name}} {{m.author.last_name}}  <span>{{m.date|date:"G:i j.n.Y"}}</span></span>

                        {% if user.is_authenticated%}
                            <span class="add_comm_btn" data-index='0'>Комментировать</span>
                        {%endif%}
                         {%ifequal m.author user%}
                            <span class='edit' class='head' >Редактировать</span>
                        {%endifequal%}
                        <hr/>
                    <div class='content'>{{m.text_massage}}</div>

                    {%if m.comments_set.all.count%}
                    <div class='show_comm' data-index='0'> Показать комментарии </div>
                    {%endif%}

                    
                    
                    </div>
                   
                </div>
               
{%endfor%}   

enot/templates/enot/index.html
<!DOCTYPE HTML>
{% load staticfiles %}
{% load poll_extras %}
<html>
        <head>
            <title>Test</title>
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/myScript.js' %}"></script>
        </head>
        <body>
        <div>
        {%include 'register/register_and_add.html'%}

        </div>
        <form  id='add_comm_form' method='post' action ='{% url "add_comm"%}'>{% csrf_token %}
            <div class='add_comm'>
                <input type='hidden' name='' value=''>
                <textarea name='text_comm' required placeholder='Оставьте комментарий'></textarea>
                <button type='submit'>Комментировать</button>
            </div>
        </form>
       
        <img id='up' style='display:none'src='{% static "images/up.png" %}'>
        </body>
</html>

enot/templates/enot/register.html
{% load socialaccount %}
<div id='reg'>
<a href="{% provider_login_url 'vk' %}">Втентакль</a>
<a href="{% provider_login_url 'facebook' %}">Лицокнига</a>
<a href="{% provider_login_url 'google' %}">Гугл плюс</a>
<p>Для добавления или комментирования сообщений выполните вход</p>

</div>

enot/templates/register/logout.html
<form id='logout' method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">Выйти</button>
</form>

enot/templates/register/register_and_add.html
{% load socialaccount %}
    <div class="mas_wrap" data-mass-id='{{m.id}}'>
        <div>
        {% if user.is_authenticated%}
            <span class='header'> Вы вошли как   {{user.first_name}} {{user.last_name}}  </span>{% include 'register/logout.html'%}
                        <hr/>
                        <form  id='form_add_mass' method='post' action='{% url "add_mass"%}'>{% csrf_token %}
                            <textarea  name ='text_mass' required placeholder='Оставьте свое сообщение' ></textarea>
                            <button type="submit" >Отправить</button>
                        </form>

        {%else%}   
            {% load staticfiles %}
                <div id='reg'>
                <a href="{% provider_login_url 'vk' %}"><div><img src='{% static "images/vk.png" %}'></div></a>
                <a href="{% provider_login_url 'facebook' %}"><div><img src='{% static "images/fb.png" %}'></div></a>
                <a href="{% provider_login_url 'google' %}"><div><img src='{% static "images/goog.png" %}'></div></a>
                
<h3>Для добавления или комментирования сообщений выполните вход</h3>
                </div>
                
        {%endif%}        
        </div>                   
    </div>
    <br/>